---
- name: Install list of packages
  apt: 
     name: "{{ packages }}"
     update_cache: yes
  vars: 
     packages: 
     - tomcat7
     - default-jdk
     - openjdk-8-jdk
     - tomcat7-admin

- name: Change default java location 
  shell: sudo update-java-alternatives --set java-1.8.0-openjdk-amd64

- name: Update tomcat access credentials
  copy: src=tomcat-users.xml dest=/etc/tomcat7/tomcat-users.xml

- name: Copy jenkins.war file to tomcat webapps folder
  copy: src=jenkins.war dest=/var/lib/tomcat7/webapps

- name: Giving ownership to tomcat7 user
  shell: chown -R tomcat7:tomcat7 /usr/share/tomcat7

#- name: Assign permissions to .jenkins home directory
#  shell: chmod 777 /usr/share/tomcat7

- name: restart tomcat 
  shell: service tomcat7 restart

